# Generated by Django 3.2.6 on 2021-09-15 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=50, verbose_name='session_id')),
                ('question_num', models.PositiveIntegerField()),
                ('policy_a', models.PositiveIntegerField()),
                ('policy_b', models.PositiveIntegerField()),
                ('policy_dataset', models.CharField(max_length=50)),
                ('user_choice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FormInfo',
            fields=[
                ('session_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='session_id')),
                ('username', models.CharField(max_length=100, null=True)),
                ('age', models.CharField(max_length=15)),
                ('race_ethnicity', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('marital_status', models.CharField(max_length=100)),
                ('education', models.CharField(max_length=100)),
                ('political', models.CharField(max_length=100)),
                ('positive_family', models.CharField(max_length=10, null=True)),
                ('positive_anyone', models.CharField(max_length=10, null=True)),
                ('healthcare_yn', models.CharField(max_length=10, null=True)),
                ('healthcare_role', models.CharField(max_length=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SessionInfo',
            fields=[
                ('session_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='session_id')),
                ('ip_address', models.GenericIPAddressField()),
                ('time_submitted', models.DateTimeField(verbose_name='date test taken')),
                ('mturker', models.BooleanField(default=False)),
            ],
        ),
    ]
