# Generated by Django 3.1.4 on 2021-08-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choices',
            fields=[
                ('session_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='session_id')),
                ('question_id', models.PositiveIntegerField()),
                ('user_choice', models.PositiveIntegerField()),
                ('left_choice', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='NextChoice',
            fields=[
                ('session_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='session_id')),
                ('previous_step', models.PositiveIntegerField()),
                ('current_step', models.PositiveIntegerField()),
                ('choice_topic', models.PositiveIntegerField()),
                ('left_choice', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SessionInfo',
            fields=[
                ('session_id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='session_id')),
                ('ip_address', models.GenericIPAddressField()),
                ('date', models.DateTimeField(verbose_name='date test taken')),
                ('mturker', models.BooleanField(default=False)),
            ],
        ),
    ]
