# Generated by Django 3.1.4 on 2021-08-19 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('APE', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NextChoice',
        ),
    ]
