# Generated by Django 3.2.6 on 2021-09-15 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessioninfo',
            name='time_submitted',
            field=models.DateTimeField(auto_now_add=True, verbose_name='date test taken'),
        ),
    ]
