# Generated by Django 3.2.6 on 2021-09-23 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='algorithm_stage',
            field=models.CharField(choices=[('adaptive', 'adaptive'), ('random', 'random'), ('validation', 'validation')], max_length=20, verbose_name='algorithm stage'),
        ),
    ]
