# Generated by Django 3.2.6 on 2021-09-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APE', '0002_alter_choices_algorithm_stage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='algorithm_stage',
            field=models.CharField(max_length=20, verbose_name='algorithm stage'),
        ),
        migrations.AlterField(
            model_name='choices',
            name='user_choice',
            field=models.CharField(choices=[('adaptive', 'adaptive'), ('random', 'random'), ('validation', 'validation')], max_length=20),
        ),
    ]
