# Generated by Django 3.2.6 on 2021-09-23 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APE', '0003_auto_20210923_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='user_choice',
            field=models.CharField(max_length=20),
        ),
    ]
