# Generated by Django 3.2.6 on 2021-09-23 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APE', '0004_alter_choices_user_choice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choices',
            name='algorithm_stage',
            field=models.CharField(max_length=50, verbose_name='algorithm stage'),
        ),
        migrations.AlterField(
            model_name='choices',
            name='question_num',
            field=models.PositiveIntegerField(verbose_name='Question Number'),
        ),
        migrations.AlterField(
            model_name='choices',
            name='session_id',
            field=models.CharField(max_length=50, verbose_name='Session ID'),
        ),
    ]
