# Generated by Django 3.1.4 on 2021-12-01 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APE', '0007_remove_sessioninfo_ip_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forminfo',
            old_name='username',
            new_name='turker_id',
        ),
        migrations.AlterField(
            model_name='choices',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
