# Generated by Django 3.1.4 on 2021-12-14 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APE', '0008_auto_20211201_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='recommended_item',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
