# Generated by Django 4.0 on 2021-12-21 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APE', '0010_alter_choices_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='choices',
            name='time_on_page',
            field=models.FloatField(null=True, verbose_name='Time Spent on Question (seconds)'),
        ),
    ]
